name: Deploy production
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: production
    steps:
      - name: build 
        run: |
          source /home/backend/.nvm/nvm.sh
          cd /opt/actions-runner/il-loss-charts
          git pull origin banana-game
          yarn config set workspaces-experimental true
          yarn
          
      - name: restart service
        run: |
          sudo systemctl restart banana-prod
